dask/templates/dask-worker-deployment.yaml

The `--no-bokeh` flag was deprecated and replaced with `--no-dashboard` in dask/distributed#2724.
This chart is still using `--no-bokeh` which breaks when using `dask-cuda-worker` as that library was added after `--no-bokeh` was deprecated and does not support it.
This PR updated the helm chart to use the newer flag.

Update worker to use --no-dashboard flag

---

dask/templates/dask-jupyter-deployment.yaml
dask/values.yaml

Users may wish to specify their own start commands for the Jupyter container.

Add jupyter container args config option

---

dask/README.md
dask/templates/dask-worker-deployment.yaml
dask/values.yaml

This allows setting a port on which workers run, instead of having randomly chosen port for each worker.
It is useful when you want to limit allowed network traffic in your cluster and have to know on which ports the nodes are allowed to talk to each other. 
It's not a problem if multiple workers run on the same port, because they are in different pods and therefore have different IPs inside the cluster.
Tested on AWS EKS cluster with network traffic limited using Security Groups.

Set worker port

---

dask/templates/dask-jupyter-config.yaml
dask/templates/dask-jupyter-deployment.yaml
dask/values.yaml

This PR moves the Jupyter config to a system location rather than the `jovyan` home directory in case folks use a container where `jovyan` isn't the default user.
I've also added a new `jupyter.extraConfig` option to the chart `values.yaml` file to allow people to easily inject extra Jupyter config.

Allow adding of extra Jupyter config via chart config

---

.github/workflows/watch-docker-hub.yml

Update the GitHub Action for getting the latest Docker image version. This now sorts semver package tags correctly.

Update Action version

---

.github/workflows/watch-docker-hub.yml

Added a check to ensure that the update versions action doesn't run on forks. Otherwise PRs are automatically raised against forks too when the version changes which isn't helpful and adds noise.

Disable version check action on forks

---

dask/templates/dask-jupyter-deployment.yaml
dask/templates/dask-scheduler-deployment.yaml
dask/templates/dask-worker-deployment.yaml
dask/values.yaml

* Add serviceAccountName to worker, scheduler, and jupyter deployments
* Add securityContext to worker and jupyter deployments
* Remove unused value from values.yaml
* Add example of EXTRA_APT_PACKAGES to worker values
* Ran `helm lint dask` without failures
* Ran `helm install dask --dry-run --debug --generate-name` without errors; observed expected behavior

add serviceAccountName to worker and jupyter deployments; formatting

---

index.md

Add the standard GitHub corner banner to help people find the source of the helm chart.
Fixes #57.

Add GitHub corner link

---

ci/release.sh
dask/README.md

This PR makes the release instructions more copy paste friendly and also adds a script to run the steps all in one go.
We should extend this in the future to have GitHub Actions do the whole thing.

First steps to automating releases

---

dask/.frigate
dask/README.md
dask/templates/dask-jupyter-serviceaccount.yaml
dask/values.yaml

This PR adds a service account and role to the Jupyter pod which allows it to manage deployments and view pods and logs.
This is limited to the namespace that the Helm Chart is deployed in but allows users to scale their cluster and access worker logs from within the bundled Jupyter session. It is enabled by default but possible to disable.
This ties in with dask/dask-docker#112 which adds `kubectl` to the notebook image and dask/dask-kubernetes#255 which adds the `HelmCluster` clusater manager.
This change should result in both `kubectl` and `HelmCluster` working without configuration from the Jupyter session provided by this chart.
cc @gforsyth

Add service account and role to allow Jupyter pod to manage workers

---

.github/workflows/frigate.yml
.travis.yml
README.md
chartpress.yaml
daskhub/.frigate
daskhub/.gitignore
daskhub/.helmignore
daskhub/Chart.yaml
daskhub/README.md
daskhub/templates/NOTES.txt
daskhub/templates/dask-kubernetes-rbac.yaml
daskhub/templates/daskhub-configmap.yaml
daskhub/templates/singleuser-configmap.yaml
daskhub/values.yaml

This implements a multi-user, dask-enabled JupyterHub helm chart that's based off the pangeo helm chart. I've called it "DaskHub" to reflect the multi-user component. The hope is that `helm install dask/dask` is for single users, and `helm install dask/daskhub` is for multiple users.
The tl/dr is "daskhub = jupyterhub + dask-gateway configured with jupyterhub auth".
The Differences from the current pangeo helm chart are
* Updated to JupyterHub 0.9.1
* Updated default singleuser image -> pangeo-notebook:2020.07.28
* Fixed incorrect hub.services.dask-gateway.url
* Removed prePuller, scheduling optimizations
* Removed extraPodConfig (preemptible nodes)
* Removed extraConfig (preemptible nodes)
* Removed custom dask-gateway options
and, most importantly, it doesn't use jupyter to proxy the …

DaskHub helm chart

---

.travis.yml

It looks like the `4.4.0` release build has failed and I suspect it is because we are not pulling the chart dependencies before packaging.
This adds a dependency update to all CI jobs.
cc @TomAugspurger

Update chart dependencies in CI

---

README.md
dask/README.md
dask/templates/dask-jupyter-deployment.yaml
dask/templates/dask-worker-deployment.yaml
dask/values.yaml

Adds volume and volume mount configs to dask helm template. #76

adding volumes and volume mounts to jupyter and worker configs

---

daskhub/Chart.yaml

JupyterHub [Helm chart `0.10.2`](https://jupyterhub.github.io/helm-chart/) has been released last week. It provides some bug fixes, new features and dependencies updates, that would be super nice to have (changelog [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md)).
What do you think?
Related issue: https://github.com/dask/helm-chart/issues/116

JupyterHub Helm chart dependency bump to 0.10.2

---

dask/README.md
dask/templates/dask-worker-deployment.yaml
dask/values.yaml

This enables setting custom annotations for workers via your config.
```yaml
worker:
annotations:
my-annotation: "hello world"
```

Make worker annotations configurable

---

.github/workflows/watch-dependencies.yml

I mistakenly thought GitHub workflows allowed the use of a `if` statement on the workflow itself, but it was only allowed on a job level. This PR fixes that error.

ci: fix syntax error in workflow

---

README.md
dask/README.md
dask/templates/dask-scheduler-service.yaml
dask/values.yaml

For `serviceType` like `LoadBalancer`, we may want to specify the the type of load balancer to use. Thus, this provides the chart users to specify it using the `annotations` field.

Added option to specify annotations in dask-scheduler-service

---

dask/templates/dask-jupyter-serviceaccount.yaml

Currently getting an error during deployment saying 
"Error: roles.rbac.authorization.k8s.io "dask-jupyter" is forbidden: user "srikanthshankara.rao@test.com" (groups=["k8s-dev-cluster-admin" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
Modifying to the correct apiGroup "apps" for deployment resolves the issue.

use apps api group for deployment

---

.github/workflows/test-dask-chart.yml
.github/workflows/test-daskhub-chart.yml
ci/common

I extracted some logic from the JupyterHub helm chart's CI system which is now available for all chart developers to use.
https://github.com/jupyterhub/action-k8s-namespace-report
I also made a pass updating some CI dependencies etc.

ci: emit k8s namespace report using dedicated github action

---

.github/workflows/publish-charts.yml

I debugged this extensively and is quite confused in general.
Lessons learned:
1. Anything we pass `git push https://<here>@github.com/org-name/repo-name.git` will be ignored. See [this job run](https://github.com/consideRatio/zero-to-jupyterhub-k8s/runs/1730071749?check_suite_focus=true) and [its associated workflow](https://github.com/consideRatio/zero-to-jupyterhub-k8s/actions/runs/496799798/workflow) for verification of that.
1. Our current failure stems from the one thing that isn't accepted, namely `https://:anything-here@github.com/org-name/repo-name.git` where we have a colon with nothing before it.
1. We experienced an issue stemming from `${{ env.GITHUB_ACTOR }}` isn't available. I think that is because the default environment variables are not available from the env context, …

ci: attempt fix of publish workflow

---

dask/templates/dask-jupyter-deployment.yaml

Hey, I noticed that the dask-jupyter-deployment template had a mistake for the Volume/VolumeMount configs for the Dask chart. Instead of using the values for the jupyter deployment, it was using the values for the worker deployment.

Fix jupyter volume mount for dask chart

---

.github/workflows/publish-charts.yml
chartpress.yaml

It seems like chartpress is behaving unexpectedly here and helm now contains most of the logic needed to package and publish charts.
Switching out to the `stefanprodan/helm-gh-pages` action which seems much simpler.

Drop chartpress in favour of helm publish action

---

README.md

Not sure how the helm cli API has changed over time, but the `--name` flag gave me grief.  Omitting it worked for me.
```
❯ helm install --name mydask dask/dask
Error: unknown flag: --name
❯ helm install mydask dask/dask
NAME: mydask
...
```

Update README to exclude `--name`

---

.github/workflows/readme-sync-check.yml
dask/README.md
daskhub/.frigate
daskhub/CHANGELOG.md
daskhub/Chart.yaml
daskhub/README.md
daskhub/values.yaml

Hi, I have successfully deployed this and tested this super simple change. While Jupyterhub has gone through quite a few changes for v1.0.0 and I needed to edit the values I use for it, the daskhub chart is super simple. You only need to configure the Jupyterhub subchart, if it is working then so is Daskhub from what I can see...
It should run as is, from what I see of your CI you could even try removing the secret https://github.com/dask/helm-chart/blob/7b32c4f6726b3fd96b118a1e8369e4b3e6115603/daskhub/dev-values.yaml#L11

2021.6.15: set Jupyterhub to 1.0.0

---

daskhub/CHANGELOG.md
daskhub/Chart.yaml

It looks like #190 modified the chartpress autogenerate version number so reverting that.
Looks like some strangeness happened with the `CHANGELOG` version too. The next version here will be `2021.6.1` as we follow `YYY.MM.PATCH` so I've updated that to be correct and I'll do a release now.
We may need to tweak the version bumping automation to ignore this file in future though.

Revert version numbers

---

.github/workflows/watch-dependencies.yml

There is a limitation of GitHub actions that PRs raised by them do not trigger CI. This is to avoid infinite loops of workflows triggering other workflows.
However this means our daily action that tried to bump versions doesn't trigger CI. The last few releases I've had to manually push an empty commit onto the PR to trigger things (e.g https://github.com/dask/helm-chart/pull/226).
This PR switches things to use a Personal Access Token belonging to @dask-bot that is stored in an org secret. This means PRs will show as authored by @dask-bot should allow CI to be triggered.

Use bot token instead of action token

---

.github/workflows/watch-dependencies.yml
dask/.frigate
dask/README.md
dask/values.yaml

Now that we push to ghcr.io and document it as the default location we should update the charts to use it.

Update all images to use ghcr.io

---

dask/templates/additional-worker-deployment.yaml
dask/templates/dask-jupyter-config.yaml
dask/templates/dask-jupyter-deployment.yaml
dask/templates/dask-jupyter-ingress.yaml
dask/templates/dask-jupyter-service.yaml
dask/templates/dask-jupyter-serviceaccount.yaml
dask/templates/dask-scheduler-deployment.yaml
dask/templates/dask-scheduler-ingress.yaml
dask/templates/dask-scheduler-service.yaml
dask/templates/dask-scheduler-servicemonitor.yaml
dask/templates/dask-worker-deployment.yaml
dask/templates/dask-worker-podmonitor.yaml

This PR makes changes to Helm chart templates in the `dask` Helm chart that doesn't lead to actual changes.
The `dask` helm chart didn't have a consistent way of doing various things overall, but this PR makes various formatting choices systematic to align with those in jupyterhub and dask-gateway.
I've made some comments among the changes to highlight the kind of changes made, because there are only a few different kinds that repeat.

maint: helm templates refactoring, systematic modern style

---

.github/workflows/publish-charts.yml
.github/workflows/test-dask-chart.yml
.github/workflows/test-daskhub-chart.yml

This will make us test against a modern version of k8s, so we will get CI failures as we don't support the latest version of k8s with daskhub 0.9.0 - but we will with the next release.

ci: test against modern k8s and misc github workflow updates

---

.github/workflows/watch-dependencies.yml
daskhub/Chart.yaml
daskhub/values.yaml

- Part 1: Our bot bumped to 2022.4.0-beta.1 instead of 2022.4.0. This was because we referenced an outdated helm chart repo for dask-gateway (closes #259).
- Part 2: Instead of looking at repo's Chart.yaml files, we reference Helm chart repositories directly to know what the latest packaged Helm chart.
- Part 3: We now also watch the pangeo/base-notebook image for new tags as it is pinned for the daskhub's values.yaml file (closes #103).
- Part 4: I ended up failing to keep this PR very clean and there are some refactoring made part of it that isn't important. I made it before I figured out the reason we bumped to 2022.4.0-beta.1 instead of 2022.4.0 for dask-gateway and thought it could relate to replace actions.
Tested to function on my fork. The test failure is because current version …

ci: watch daskhub's singleuser image and misc updates to watch workflow

---

.github/workflows/watch-dependencies.yml
dask/values.yaml

This PR replaces the use of https://github.com/jacobtomlinson/gha-get-docker-hub-tags which was only usable for dockerhub and had an issue with stripping away leading zeroes (https://github.com/jacobtomlinson/gha-get-docker-hub-tags/issues/7).
The new strategy adopted is to use the skopeo docker image which helps us get tags from any container registry. These tags are then filtered and sorted with a `jq` expression.

ci: detect latest x.y.z tag from any container registry

---

.github/workflows/watch-dependencies.yml

I think this should be fix #272.

ci: fix broken references for watch-dependencies.yaml jobs

---

.github/workflows/watch-dependencies.yml

xref https://github.com/dask/helm-chart/issues/267
cc @jacobtomlinson and @consideRatio (since you might have been looking at this). I'm not sure why this is necessary, but it seems to do the trick.
The old one
```
❯ docker run -it --rm -e INPUT_INCLUDE="dask" -e INPUT_FIND=2022.5.0 -e INPUT_REPLACE=2022.5.1 -v (pwd):/github/workspace -v (pwd):/github/home -v (pwd):/github/workflow jacobtomlinson/gha-find-replace:2.0.0
::set-output name=modifiedFiles::0
```
The new one
```
❯ docker run -it --rm -e INPUT_INCLUDE="**/dask/*" -e INPUT_FIND=2022.5.0 -e INPUT_REPLACE=2022.5.1 -v (pwd):/github/workspace -v (pwd):/github/home -v (pwd):/github/workflow jacobtomlinson/gha-find-replace:2.0.0
::set-output name=modifiedFiles::4
```

ci: Fixup the replace string

---

index.yaml

It seems that the old dask-gateway helm chart repo isn't active any more, but since we migrated the content from it to this, I think we can just update the urls.
I'll go for a self-merge on this to be able to followup with possible issues and unblock my work to fix issues in dask-gateway, where the CI system broke due to failing to acquire the 0.9.0 helm chart due to a broken link.

Fix broken helm chart repo urls

---

.github/workflows/watch-dependencies.yml

This PR is meant to provide debugging output and abort before creating a PR if we experience a intermittent bug as observed in https://github.com/dask/helm-chart/pull/303.

ci: fail loudly and emit debugging info if new version is a blank string

---

.github/workflows/watch-dependencies.yml
daskhub/Chart.yaml

The daskhub helm chart had a Chart.yaml with `appVersion` based on ghcr.io/dask/dask's image latest version. That didn't make sense as daskhub is not dependent on that in any way. It is dependent on jupyterhub helm chart and dask-gateway helm chart.
By chance, we were running into issues where daskhub's referenced dask-gateway helm chart version of 2022.6.1 were updated. But, since we should not update daskhub in any way if ghcr.io/dask/dask gets a new release, this can be avoided altogether.
Going onwards, the daskhub/Chart.yaml's appVersion field represent the jupyterhub helm chart version and dask-gateway helm chart version instead, and we avoid this kind of failures as observed in https://github.com/dask/helm-chart/pull/294 caused by an irrelevant change.

Let daskhub's appVersion reflect its dependency helm chart's versions

---

dask/templates/dask-jupyter-ingress.yaml
dask/templates/dask-scheduler-ingress.yaml

I could not make ingress values work. Example bellow:
```
cat << EOF >> myvalues.yaml
webUI:
servicePort: 80
ingress:
enabled: true
annotations:
kubernetes.io/ingress.class: traefik
traefik.frontend.entryPoints: "http"
traefik.ingress.kubernetes.io/router.entrypoints: http
jupyter:
ingress:
enabled: true
annotations:
kubernetes.io/ingress.class: traefik
traefik.frontend.entryPoints: "http"
traefik.ingress.kubernetes.io/router.entrypoints: http
EOF
```
This fixes the issue

Fix dask ingress annotation substitution

---

dask/templates/NOTES.txt

Hi, there.
When I use the helm chart for deploying the dask cluster, I think it's more convenient to use the subcommand `helm get all` to get all deployment YAML of the dask cluster for users.

Add subcommand for helm get

---

.github/workflows/publish-charts.yml
.github/workflows/test-dask-chart.yml
.github/workflows/test-daskhub-chart.yml
.github/workflows/watch-dependencies.yml

By pinning to the major version only, we avoid cluttering PRs that bump patch versions of something in the CI system.
- Closed #340 in favor of this.

ci: bump sustainably between major versions only

---

daskhub/.frigate

The example code in the Daskhub Helm chart README errors because it references a `gateway` variable that doesn't exist. This PR corrects this to what I think y'all were going for -- instantiating the cluster directly from `dask_gateway.GatewayCluster()` rather than a `dask_gateway.Gateway` instance.
Thanks for everything!

Fix bad Daskhub README example code

---

dask/templates/dask-jupyter-deployment.yaml
dask/values.yaml

Having multiple Jupyter replicas doesn't really make sense. I assume this config option is a holdover from the `helm init` command. Removing it to avoid people accidentally configuring it to something other than `1`.

Remove config option for Jupyter replicas

---

dask/templates/dask-jupyter-deployment.yaml
dask/templates/dask-scheduler-deployment.yaml
dask/templates/dask-worker-deployment.yaml
dask/values.yaml

This PR adds liveness and readiness probe to worker, scheduler and jupyter deployment. Closes #367 .
The probes used to test the healthiness of each deployment are:
Worker:
- http: 8790
- path: /status, /health
Scheduler:
- http: 8787
- path: /status, /health
Jupyter:
- http: 8888
- path: /login

Adds Liveness and Readiness Probe to Worker, Scheduler and Jupyter Deployment

---

dask/templates/NOTES.txt
dask/values.yaml

When you install the dask/dask helm chart the `NOTES.txt` prints out that the default password for Jupyter is `dask`.
However if the user configures the password hash to be something different the notes text still says it is Dask. This PR adds another config option that also makes the notes text configurable.
Ideally I'd like to remove the hash altogether and have the user configure the password, and the has be generated as part of rendering the template. But that seemed overly complicated and introduced new dependencies to the `helm install` so this seemed like a simpler if less elegant option.

Make password hint configurable

---

.github/workflows/test-dask-chart.yml
.github/workflows/test-daskhub-chart.yml

The daskhub chart had failing tests because the jupyterhub chart had dropped support for k8s 1.20 which at this point in time is ancient. I'm increasing the lower bound tested from 1.20 to 1.24 for both charts.
TLDR: we previously tested k8s 1.20 and ~most recent version, but now we test k8s 1.24 and ~most recent version

ci: test lower k8s version 1.24 instead of 1.20

---

dask/templates/dask-worker-deployment.yaml

Update worker deployment template to allow detailed customization of the 'strategy' field using the 'Values.yaml'.
It enables users to specify more granular settings for the deployment strategy, including sub-properties, providing control over the deployment of workers.

Allow arbitrary configuration under worker deployement's `strategy` (previously only `type`)

---

dask/values.yaml

It is used in the scheduler deployment:
https://github.com/dask/helm-chart/blob/50b457f00bb5a7b81c9f5033b3be372473b7b407/dask/templates/dask-scheduler-deployment.yaml#L52
but not modifiable through `values.yaml`.
There is now a feature parity with the `.Values.worker.env` and the worker deployment.

add env to scheduler to values.yaml
