dask/helm-chart

- dask/Chart.yaml
- dask/README.md
- dask/templates/dask-jupyter-deployment.yaml
- dask/templates/dask-scheduler-deployment.yaml
- dask/templates/dask-worker-deployment.yaml
- dask/values.yaml
Addresses #1899 for the dask-distributed charts, adding a nodeSelector option to the configs.
Not sure if this is the right place to be sending a PR, would love some input or pointers.
@bnaul
> Add nodeSelector to helm chart

- dask/templates/dask-worker-deployment.yaml
Limits for workers were not correctly passed from the configuration to the template
> [bugfix] fix worker limits typo

- dask/Chart.yaml
- dask/values.yaml
Bump Dask version to 2.8.0. (Still working on automating this in slower time).
> Update Dask to 2.8.0

- dask/README.md
> DOC: fix link to values.yaml

- dask/templates/dask-worker-deployment.yaml
- dask/values.yaml
> Option to customize --nthreads

- dask/values.yaml
> Make ClusterIP the default service type

- index.md
Currently the tables are not formatted properly on the rendered helm.dask.org
I haven't built this locally yet to verify that it fixes things.
> Fixed table formatting

- .github/workflows/watch-docker-hub.yml
- ci/release.sh
- dask/Chart.yaml
- daskhub/Chart.yaml
> Prepare for DaskHub

- daskhub/.frigate
- daskhub/README.md
Closes https://github.com/dask/helm-chart/issues/104
> Update extraConfig example

- index.md
This provides instructions for both.
> Update install instructions for helm3

- dask/README.md
- dask/templates/dask-scheduler-deployment.yaml
- dask/values.yaml
Closes #85
Also fixed some typos
> Add SecurityContext to the scheduler deployment

- dask/README.md
- dask/templates/dask-scheduler-deployment.yaml
- dask/templates/dask-worker-deployment.yaml
- dask/values.yaml
Fixes #115 
Adds config options for extra command line arguments for the scheduler and workers.
> Allow extra scheduler/worker args

- daskhub/.frigate
- daskhub/README.md
Forgot to update it last time, and will probably forget in the future. This will ensure people get the latest.
> Remove version from install command

- .github/workflows/publish-charts.yml
See https://github.com/dask/helm-chart/issues/140
Not sure if this will work- this is an attempt at getting the `GITHUB_TOKEN` included with GitHub workflows to work with chartpress.
> Try including GITHUB_ACTOR with GITHUB_TOKEN

- .github/workflows/publish-charts.yml
Nothing important in this release, just keeping it updated.
> Bump chartpress to 1.0.0

- .github/workflows/publish-charts.yml
Misunderstood how to configure the action.
> Tweak release CI

- dask/README.md
- dask/templates/dask-worker-deployment.yaml
- dask/values.yaml
> Allow configuration of worker deployment strategy

- daskhub/Chart.yaml
Once upon a time, I though I would have enough time to work on this chart regularly, and just added myself as a maintainers. This was so unrealistic and unmodest from my part, sorry for this :).
> Remove myself from the maintainers

- .gitattributes
GitHub strangely reports this repo as moustache language. Just playing around to see if I can override that.
> Explicitly set languages used

- .gitattributes
> File languages 2

- .github/workflows/watch-dependencies.yml
Looks like #235 broke the watching action. Reverting for now.
> Revert check dask image org

- dask/templates/dask-jupyter-ingress.yaml
Refer to #239 for details
Fixes #239
> :bug: Fix whitespace error that caused invalid Helm render

- .github/workflows/test-dask-chart.yml
- dask/templates/dask-jupyter-ingress.yaml
- dask/templates/dask-scheduler-ingress.yaml
- dask/values.yaml
updates ingress api version and its spec in the schduler webUI ingress template for current k8s versions.
> resolves #224

- .github/workflows/watch-dependencies.yml
- dask/Chart.yaml
- daskhub/Chart.yaml
I think #275 was only a partial fix, this I think is the full fix by adding `regex: false`.
I refactored the logic a bit as well and added a FIXME note.
> ci: fix use of string replacement action

- .github/workflows/watch-dependencies.yml
Hopefully closes #308.
---
Going for a self-merge as this is broken and this is a possible fix that may or may not work and I look to verify it quickly to avoid context switch to doing it later.
> ci: fix automation with gha-find-replace action

- .github/workflows/watch-dependencies.yml
- Followup after #309 didn't do the trick. Hopefully properly closes #308.
> ci: attempt to fix automation without dedicated gha

- .github/workflows/watch-dependencies.yml
I saw in #311 that the PR comment was no longer accurate following #305 was merged.
> ci: update pr comment

- dask/.helmignore
- daskhub/.helmignore
> Remove README.md from .helmignore

- dask/templates/dask-scheduler-deployment.yaml
> dask chart: migrate deprecated CLI flag --bokeh-port
